name = "cf-workers-telegram-bot-v2"
main = "packages/worker/src/worker.ts"

workers_dev = true
compatibility_date = "2024-05-13"

[placement]
mode = "smart"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "852b4f27-5f16-4540-b808-7b601880ba85"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"
